### PR TITLE
parse destinationDirectory path to replace field

### PR DESCRIPTION
**Pull request by Stereobit**
@mattvagni would love this as I have components in container specific folders and I like to have a question for it

### CODE REVIEW

**Comment by mattvagni** [comment]
@Stereobit not sure if I understand correctly but I think what you are trying to do is already possible.

Let's just say your template is in `templates/COMPONENT_NAME` if you set the output directory to `src/components` and have a question for `COMPONENT_NAME` then you will get `src/components/MyComponent`.

**Comment by Stereobit** [comment]
@mattvagni no, I want to create a component in an existing container folder like `/containers/homepage/components/`

I ask for that folder in a separate question.

**Comment by mattvagni** [comment]
Ok - can you please update the readme? Happy to merge this then.

**Comment by mattvagni** [comment]
@Stereobit ping ;)

**Pull request closed without merging**
